### ISSUE TITLE
Move MSTestEx to .NET Core 2.0

### ISSUE THREAD

**Issue by pvlakshm** [pvlakshm/MSTestEx#165]

**Comment by AJua** [comment]
The latest .NET Core release lifecycles move quite fast. .NET Core 2.0 is treated as end of life already. How about moving to .NET Core 3.1? 
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Version | Original Release Date | Latest Patch Version | Patch Release Date | Support Level | End of Support
-- | -- | -- | -- | -- | --
.NET Core 3.1 | December 3, 2019 | 3.1.2 | February 18, 2020 | LTS | December 3, 2022
.NET Core 3.0 | September 23, 2019 | 3.0.3 | February 18, 2020 | EOL | March 3, 2020
.NET Core 2.2 | December 4, 2018 | 2.2.8 | November 19, 2019 | EOL | December 23, 2019
.NET Core 2.1 | May 30, 2018 | 2.1.16 | February 18, 2020 | LTS | August 21, 2021
.NET Core 2.0 | August 14, 2017 | 2.0.9 | July 10, 2018 | EOL | October 1, 2018

**Comment by pvlakshm** [comment]
Thank you for the feedback. Will look into this in the coming few days.

**Comment by pvlakshm** [comment]
Upgraded to latest dependencies. Refer #175
